### ISSUE TITLE
symbol lookup error on jazzy-testing and rolling-testing

### ISSUE THREAD

**Issue by christophfroehlich** [ros2/rosidl_typesupport_fastrtps#126]
Since last night we get strange errors in all ros2_control jazzy-testing CI jobs, e.g. [here](https://github.com/ros-controls/ros2_control_ci/actions/runs/12424310099/job/34689257813). Is this known already, is this the right place here to report?

Python tests
```
[spawner-3] /usr/bin/python3: symbol lookup error: /opt/ros/jazzy/lib/libcontroller_manager_msgs__rosidl_typesupport_fastrtps_c.so: undefined symbol: _ZN8eprosima7fastcdr3Cdr9serializeERKh
```

c++ tests
```
/home/runner/work/ros2_control_ci/ros2_control_ci/.work/target_ws/build/realtime_tools/realtime_server_goal_handle_tests: symbol lookup error: /opt/ros/jazzy/lib/libtest_msgs__rosidl_typesupport_fastrtps_cpp.so: undefined symbol: _ZN8eprosima7fastcdr3Cdr9serializeEa
```

[clang](https://github.com/ros-controls/realtime_tools/actions/runs/12437594628/job/34727791218) also complains on rolling at build time
```
  /usr/bin/ld: /opt/ros/rolling/lib/libtest_msgs__rosidl_typesupport_fastrtps_c.so: undefined reference to `eprosima::fastcdr::Cdr::serialize(signed char)'
```

However, here it seems to be fine
https://build.ros2.org/job/Jbin_uN64__rosidl_typesupport_fastrtps_cpp__ubuntu_noble_amd64__binary/

**Required Info:**

- Operating System:
  - ubuntu noble
- Installation type:
  - binary
- Version or commit hash:
  - jazzy testing
- DDS implementation:
  - fastrtps
- Client library (if applicable):
  - N/A

**Comment by clalancette** [comment]
@marcoag FYI

**Comment by MiguelCompany** [comment]
I think this might be my fault. The last release of fastcdr includes one change that might be an ABI break, which I didn't realize.

The failures seem to have started to happen when https://github.com/ros/rosdistro/pull/43968 and https://github.com/ros/rosdistro/pull/43967 were merged

I think this is due to https://github.com/eProsima/Fast-CDR/pull/210, where some exported methods changed from being implemented in the header to the source.

I suggest to bloom-release fastcdr v2.2.5, and fix the .repos to that version while we are on holidays.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-12-23/41213/2

**Comment by marcoag** [comment]
@MiguelCompany are you guys blooming v2.2.5 anytime soon or shall I take care of it?

**Comment by MiguelCompany** [comment]
@marcoag Almost all of us are on holidays. Would be great if you can take care of it.

**Comment by christophfroehlich** [comment]
Thanks @marcoag jazzy is fixed now, but rolling still needs the release right?

**Comment by marcoag** [comment]
Yup, rolling could use a downgrade. Sorry I was only focused on fixing jazzy. Thanks for the ping @christophfroehlich!

**Comment by christophfroehlich** [comment]
Thanks again, our CI jobs with jazzy and rolling are fine now. Should I keep this issue open for a proper fix instead of the downgrade?

**Comment by clalancette** [comment]
Nah, I'm going to close it for now.  We can always reopen in the future if we run into more problems.  I will note that an ABI break is perfectly acceptable for Rolling.

**Comment by christophfroehlich** [comment]
> I will note that an ABI break is perfectly acceptable for Rolling.

Sure, but somehow did the binaries from the build farm fail. Was there any package not rebuilt, resulting in incompatible binaries?
