### ISSUE TITLE
No get_service_type_support_handle[...] function generated?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rosidl_typesupport_fastrtps#3]
I noticed that fastrtps static is the only typesupport not generating service typesupport handle function for the generated services (such as https://github.com/ros2/rosidl/blob/692b66b0128d1098b5052dc126dfb184a69c1c21/rosidl_typesupport_introspection_cpp/resource/srv__type_support.cpp.em#L64-L67).

Is it on purpose?
Should these functions be generated for all type supports?

@dirk-thomas @MiguelCompany

**Comment by dirk-thomas** [comment]
This is going to be challenging to answer without a deep dive into the type support code base again.

I think the symbol exists that user code would have the opportunity to access the handle if they want to. All code in `rclcpp` etc. goes through the indirection of `rosidl_typesupport_cpp` though which itself accesses the internal handle from each type support and doesn't the templated function.

So if my memory / assumptions are right it isn't strictly necessary but could be useful to have. I would be fine leaving it out until we have a need for it...
