### ISSUE TITLE
Shared library build when `BUILD_SHARED_LIBS` is set to `OFF`

### ISSUE THREAD

**Issue by mlanas** [ros2/rosidl_typesupport_fastrtps#97]
## Bug report

**Required Info:**

- Operating System: 
  - Ubuntu 22.04 (Docker)
- Installation type: 
  - source
- Version or commit hash: 
  - humble
- DDS implementation: 
  - Fast-RTPS

#### Steps to reproduce issue

```
FROM docker.io/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

RUN apt-get update && apt-get install -y \
	locales \
	software-properties-common \
	curl gnupg lsb-release

RUN locale-gen en_US en_US.UTF-8 &&\
	update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 &&\
	add-apt-repository universe
	
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg &&\
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt-get update && apt-get install -y \
	python3-flake8-docstrings \
	python3-pip \
	python3-pytest-cov \
	ros-dev-tools \
	python3-flake8-blind-except \
	python3-flake8-builtins \
	python3-flake8-class-newline \
	python3-flake8-comprehensions \
	python3-flake8-deprecated \
	python3-flake8-import-order \
	python3-flake8-quotes \
	python3-pytest-repeat \
	python3-pytest-rerunfailures

WORKDIR /root/ros2_humble
RUN mkdir -p /root/ros2_humble/src
RUN vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src
RUN apt-get update && apt-get upgrade -y && rosdep init && rosdep update &&\
	rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"

RUN colcon build \
	--cmake-args '-DBUILD_SHARED_LIBS=OFF' \
	--packages-up-to rosidl_typesupport_fastrtps_cpp
```

Build the above Dockerfile.

#### Expected behavior

A static library (`librosidl_typesupport_fastrtps_cpp.a`) should be build when the `BUILD_SHARED_LIBS` flag is set to `OFF`.

#### Actual behavior

A shared library (`librosidl_typesupport_fastrtps_cpp.so`) is build when the `BUILD_SHARED_LIBS` is set to `OFF`.

#### Additional information

The library is apparently build as `SHARED` in https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_cpp/CMakeLists.txt#L45
Removing the `SHARED` keyword results in the expected behavior. This change was done in several ros2 projects (see https://github.com/ros2/ros2/issues/306).

**Comment by clalancette** [comment]
@tylerjw FYI
